### ISSUE TITLE
Program does not work for number of sites < 6

### ISSUE THREAD

**Issue by hyanwong** [SajadMirzaei/RentPlus#2]
E.g. with a test file

```
2792 4277 4666 4693 
0001
1001
0001
0001
0001
0101
1001
1001
0010
0101
```

I get `Making Distance MatricesException in thread "main" java.lang.IndexOutOfBoundsException: Index: 5, Size: 4`

**Comment by hyanwong** [comment]
This might be the same bug as https://github.com/SajadMirzaei/RentPlus/issues/3, not a number of sites issue

**Comment by SajadMirzaei** [comment]
Thank you for bringing up the issues. They are both fixed and the src folder and the new jar file are updated.
